[book]
authors = ["m0ham3dx"]
language = "en"
multilingual = false
src = "src"
title = "m0ham3dx - Immunefi - White Hat Scholarship - Report"

[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = true     # displays line numbers for editable code
runnable = true          # displays a run button for rust code

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "Ayu"
mathjax-support = true # Enabling MathJax Support 
git-repository-url = "https://github.com/m0ham3dx/Immunefi-WHS-Report"
git-repository-icon = "fa-github"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.print]
enable = false    # include support for printable output
page-break = false # insert page-break after each chapter
